// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1R4SnOS0oWL2w7jh8amz9lr9rRBQ7qcM',
    appId: '1:461006571114:web:1d6b74b985ef0097812c13',
    messagingSenderId: '461006571114',
    projectId: 'prathamesh-47340',
    authDomain: 'prathamesh-47340.firebaseapp.com',
    storageBucket: 'prathamesh-47340.appspot.com',
    measurementId: 'G-P0FRGF7T7K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbSdGCUY67EQ0tjHUSJv7-NJ_TTQQebDA',
    appId: '1:461006571114:android:d272d1cd09e45b83812c13',
    messagingSenderId: '461006571114',
    projectId: 'prathamesh-47340',
    storageBucket: 'prathamesh-47340.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwUijU0cEAzG4qlQKJJEg1cy6vczORoJI',
    appId: '1:461006571114:ios:983f25a789a562cd812c13',
    messagingSenderId: '461006571114',
    projectId: 'prathamesh-47340',
    storageBucket: 'prathamesh-47340.appspot.com',
    iosBundleId: 'com.example.flashChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwUijU0cEAzG4qlQKJJEg1cy6vczORoJI',
    appId: '1:461006571114:ios:bcfba4041f468172812c13',
    messagingSenderId: '461006571114',
    projectId: 'prathamesh-47340',
    storageBucket: 'prathamesh-47340.appspot.com',
    iosBundleId: 'com.example.flashChat.RunnerTests',
  );
}
